/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const RequestType = t.enumtype({
  "SignUp": "signup",
  "AddUserToClinic": "addUserToClinic",
  "NewRecording": "newRecording",
  "GetRecording": "getRecording",
});

export const BeatRequest = t.iface([], {
  "type": "RequestType",
  "username": "string",
  "password": "string",
});

export const ECG = t.iface([], {
  "I": t.opt("string"),
  "II": t.opt("string"),
  "III": t.opt("string"),
  "aVR": t.opt("string"),
  "aVL": t.opt("string"),
  "aVF": t.opt("string"),
  "V1": t.opt("string"),
  "V2": t.opt("string"),
  "V3": t.opt("string"),
  "V4": t.opt("string"),
});

export const ECGMeta = t.iface([], {
  "leads": t.array("string"),
  "numSamples": t.array("number"),
  "sampleRate": "number",
  "startTime": "number",
});

export const UploadRequest = t.iface(["BeatRequest"], {
  "type": t.enumlit("RequestType", "NewRecording"),
  "ecg": "ECG",
  "sampleRate": "number",
  "startTime": "number",
});

export const DownloadRes = t.iface([], {
  "ecg": "ECG",
  "sampleRate": "number",
  "startTime": "number",
});

const exportedTypeSuite: t.ITypeSuite = {
  RequestType,
  BeatRequest,
  ECG,
  ECGMeta,
  UploadRequest,
  DownloadRes,
};
export default exportedTypeSuite;
